#Requires -Version 7
# Writes the app's string resources from the tables in CONTENT.md, which is the only place UI words are edited.
# With -Check, writes nothing and fails if the resources differ from CONTENT.md.
param([switch]$Check)
$ErrorActionPreference = 'Stop'
[Console]::OutputEncoding = [Text.Encoding]::UTF8
$root = Split-Path $PSScriptRoot -Parent
$resources = Join-Path $root 'src/KindlyBartender.App/Resources'

$english = [ordered]@{}
$korean = [ordered]@{}
$inStrings = $false
foreach ($line in Get-Content (Join-Path $root 'CONTENT.md') -Encoding utf8) {
    if ($line -match '^## ') {
        $inStrings = $line -eq '## Strings'
        continue
    }
    if (-not $inStrings -or $line -notmatch '^\|' -or $line -match '^\| (ID |---)') {
        continue
    }
    # Exactly three non-empty cells. A pipe inside a string would split it silently, so such a row fails instead.
    if ($line -notmatch '^\|([^|]+)\|([^|]+)\|([^|]+)\|\s*$' -or
        -not ($Matches[1].Trim() -and $Matches[2].Trim() -and $Matches[3].Trim())) {
        throw "Malformed string row in CONTENT.md: $line"
    }
    $id = $Matches[1].Trim()
    if ($english.Contains($id)) {
        throw "Duplicate string ID in CONTENT.md: $id"
    }
    $english[$id] = $Matches[2].Trim()
    $korean[$id] = $Matches[3].Trim()
}

function ConvertTo-Resx([System.Collections.Specialized.OrderedDictionary]$strings) {
    $builder = [Text.StringBuilder]::new()
    [void]$builder.AppendLine('<?xml version="1.0" encoding="utf-8"?>')
    [void]$builder.AppendLine('<!-- Generated by scripts/Sync-Strings.ps1 from CONTENT.md. Edit CONTENT.md, not this file. -->')
    [void]$builder.AppendLine('<root>')
    [void]$builder.AppendLine('  <resheader name="resmimetype"><value>text/microsoft-resx</value></resheader>')
    [void]$builder.AppendLine('  <resheader name="version"><value>2.0</value></resheader>')
    [void]$builder.AppendLine('  <resheader name="reader"><value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>')
    [void]$builder.AppendLine('  <resheader name="writer"><value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>')
    foreach ($id in $strings.Keys) {
        $value = [Security.SecurityElement]::Escape($strings[$id])
        [void]$builder.AppendLine("  <data name=""$id"" xml:space=""preserve""><value>$value</value></data>")
    }
    [void]$builder.AppendLine('</root>')
    $builder.ToString().Replace("`r`n", "`n")
}

$files = @{
    (Join-Path $resources 'Strings.resx') = ConvertTo-Resx $english
    (Join-Path $resources 'Strings.ko.resx') = ConvertTo-Resx $korean
}

$stale = @()
foreach ($path in $files.Keys) {
    $current = if (Test-Path $path) { (Get-Content $path -Raw -Encoding utf8).Replace("`r`n", "`n") } else { '' }
    if ($current -ne $files[$path]) {
        if ($Check) {
            $stale += $path
        }
        else {
            New-Item -ItemType Directory -Force -Path $resources | Out-Null
            [IO.File]::WriteAllText($path, $files[$path], [Text.UTF8Encoding]::new($false))
            Write-Host "Wrote $path"
        }
    }
}

if ($stale) {
    $stale | ForEach-Object { Write-Host "$_ differs from CONTENT.md; run scripts/Sync-Strings.ps1." }
    exit 1
}
Write-Host "String resources match CONTENT.md ($($english.Count) strings)."
exit 0
